# This is a basic workflow to help you get started with Actions

name: Test & Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: 14.9.0
      - run: node test
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          USERNAME: ${{ secrets.DEPLOYMENT_USERNAME }}
          KEY: ${{ secrets.DEPLOYMENT_SSHKEY }}
          script: ./deploy.sh
